spring:
  datasource:
    username: root
    password: '&Ljy610325'
    url: jdbc:mysql://47.103.199.33:3306/mogu_blog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    static-path-pattern: /**
    servlet:
      path: /

jwt:
  secret: secret
  expiration: 7200000
  token: Authorization

server:
  port: 8601


